### PR TITLE
Fix accounts profile

### PR DESCRIPTION
**Pull request by micchickenburger**
Getting accounts tab ready for prime time.

### CODE REVIEW

**Comment by micchickenburger** [comment]
@eoghanTadhg Can you double-check the styles of the subscriptions tab?  The subscriptions and listservs had description text, but it was hard-coded lorem ipsum.  I changed that to dynamic helper `{{description}}`, but did not define any since I figured they were all self-explanatory.  However, the main text is no longer perfectly aligned vertically.

**Comment by eoghanTadhg** [comment]
@micchickenburger , Unfortunately originally designed for just handling a title, the description was added after the fact, thus margins were adjusted to align both lines center with the toggle switches.

Short of rebuilding that section using `display:table` `display:table-cell` and `vertical-align` properties, it could not be accomplished with great ease.

We can open a new ticket to improve that feature?
In the meantime, we modify the margins to accomodate w/ description or w/o.

Thoughts?

**Comment by micchickenburger** [comment]
@eoghanTadhg Sure, let's just modify the margins for now.

**Comment by eoghanTadhg** [comment]
@micchickenburger, I've adjusted the margin accordingly.

**Review by eoghanTadhg — APPROVED** [review]

**Pull request merged**
